package com.example.cars4sale.DataGenerator;

public class StringData {
    //all car name, when we random to create car name, it can select from this.
    static String[] carModelName = {
            "ACURA MDX A-Spec", "ACURA ILX", "ACURA TLX", "ALFA ROMEO Stelvio Quadrifoglio",
            "ALFA ROMEO MiTo", "ALFA ROMEO Giulia GTA", "ALPINE A106", "ALPINE A108",
            "ALPINE A110S", "ARIEL Atom 3", "ARIEL Atom 500 V8", "ARIEL Nomad", "ARO M59",
            "ARO M 461", "ARO 24", "ASTON MARTIN DBX", "ASTON MARTIN DB11",
            "ASTON MARTIN Vantage Roadster", "AUDI S5 Cabriolet", "AUDI S4", "AUDI SQ5",
            "BENTLEY Mulliner Bacalar", "BENTLEY Bentayga", "BMW X7", "BMW 8-Series Convertible",
            "BMW 7 Series LCI", "BRISTOL Fighter T", "BRISTOL Series 6", "BRISTOL Bullet",
            "BUFORI MK I", "BUFORI MK II", "BUFORI V6i", "BUGATTI Centodieci",
            "BUGATTI Chiron Super Sport 300+", "BUGATTI Chiron Pur Sport", "BUICK Encore GX",
            "BUICK Regal", "BUICK Regal Sportback", "CADILLAC CT5-V", "CADILLAC XT5",
            "CADILLAC Escalade", "CATERHAM Superlight", "CATERHAM Seven 620 R",
            "CATERHAM Super Seven 1600", "CHEVROLET Traverse", "CHEVROLET SS", "CHEVROLET Sonic",
            "CHRYSLER 300", "CHRYSLER Pacifica", "CITROEN C3", "CITROEN AMI", "CITROEN C4",
            "CUPRA Formentor", "CUPRA Leon 5 doors", "CUPRA el-Born", "DACIA Logan",
            "DACIA Sandero", "DAEWOO Nubira Estate", "DAEWOO Nubira Hatchback", "DAEWOO Matiz",
            "DAIHATSU Cuore", "DAIHATSU Ayla", "DAIHATSU Sirion", "DATSUN GO+", "DATSUN on-Do",
            "DATSUN Mi-Do", "DeLorean DMC-12", "DODGE Charger SRT Hellcat Widebody",
            "DODGE Durango", "DODGE Durango SRT", "DONKERVOORT D8", "DR MOTOR dr2",
            "DR MOTOR dr5", "DR MOTOR dr CityCross", "DS AUTOMOBILES DS 5",
            "DS AUTOMOBILES DS 3 Crossback", "DS AUTOMOBILES DS 9", "FERRARI F8 Spider",
            "FERRARI Roma", "FERRARI Portofino M", "FIAT 500e", "FIAT Freemont Cross", "FIAT Doblo",
            "FISKER Karma", "FORD F-150 Super Crew", "FORD F-150 Raptor SVT", "FORD C-Max",
            "FSO Polonez Caro", "FSO Polonez Kombi", "FSO Prima", "GEELY CK", "GEELY MK2 (Hatch)",
            "GEELY Emgrand EC718", "GENESIS G90", "GENESIS GV80", "GENESIS G80",
            "GMC Sierra Denali", "GMC Sierra 2500HD", "GMC Acadia", "GTA Motor GTA Spano",
            "HINDUSTAN Ambassador", "HINDUSTAN Pushpak", "HINDUSTAN RTV", "HOLDEN Commodore",
            "HOLDEN Captiva", "HOLDEN Trax", "HONDA CR-V", "HONDA Jazz", "HONDA Odyssey",
            "HUMMER H2 SUT", "HUMMER H3", "HUMMER H3 Alpha", "HYUNDAI Elantra N Line",
            "HYUNDAI Tucson", "HYUNDAI i30 N", "INFINITI QX70", "INFINITI Q60", "INFINITI EX37",
            "ISUZU MU-7", "ISUZU D-Max Double Cab", "ISUZU D-Max Arctic Trucks AT35",
            "JAGUAR F-Type Convertible", "JAGUAR XFR", "JAGUAR F-Pace", "JEEP Gladiator",
            "JEEP Renegade", "JEEP Compass", "Karma Revero GT", "Karma Revero GTS",
            "KIA Picanto 5 doors", "KIA Rio", "KIA K5", "KOENIGSEGG Agera RS", "KOENIGSEGG Jesko",
            "KOENIGSEGG Gemera", "KTM X-Bow R", "KTM X-Bow RR", "KTM X-Bow GT", "LADA Kalina Sedan",
            "LADA Kalina Hatchback", "LADA Priora", "LAMBORGHINI Sian",
            "LAMBORGHINI Huracan Evo RWD", "LAMBORGHINI Sian Roadster", "LANCIA Ypsilon",
            "LANCIA Delta", "LANCIA Ypsilon", "LAND ROVER Discovery Sport",
            "LAND ROVER Defender 90", "LAND ROVER Defender 110", "LEXUS LC 500 Convertible",
            "LEXUS IS", "LEXUS LS", "LINCOLN Aviator", "LINCOLN Corsair", "LINCOLN Navigator L",
            "LOTUS Exige 410 Sport", "LOTUS Evija", "LOTUS Evora GT", "Mahindra Bolero",
            "Mahindra Thar", "Mahindra Verito", "MARUSSIA B1", "MARUSSIA B2",
            "MARUTI SUZUKI Wagon R", "MARUTI SUZUKI Zen Estilo", "MARUTI SUZUKI Ciaz",
            "MASERATI Ghibli Trofeo", "MASERATI Quattroporte Trofeo", "MASERATI MC20",
            "MAYBACH 57 Zeppelin", "MAYBACH 62 Zeppelin", "MAYBACH Landaulet", "MAZDA MX-30",
            "MAZDA 2", "MAZDA BT-50", "MCLAREN Elva", "MCLAREN 620R", "MCLAREN 765LT",
            "MCLAREN 765LT", "MERCEDES BENZ A-Class", "MERCEDES BENZ B-Class",
            "MERCEDES BENZ C-Class", "MERCEDES BENZ E-Class", "MERCEDES BENZ G-Class",
            "MERCEDES BENZ S-Class", "MERCEDES BENZ EQC", "Mercedes-Benz AMG GT C", "MERCURY Milan",
            "MERCURY Grand Marquis", "MERCURY Mariner", "MG GS", "MG ZS", "MG HS", "MINI Clubman",
            "MINI John Cooper Works GP", "MINI Countryman", "MITSUBISHI ASX",
            "MITSUBISHI Mirage GT", "MITSUBISHI Mirage", "MORGAN Aero 8", "MORGAN Plus Six",
            "MORGAN Plus Four", "NISSAN Sentra", "NISSAN Rogue", "OLDSMOBILE Aurora",
            "OLDSMOBILE Aurora", "OLDSMOBILE Intrigue", "OPEL Sports Tourer",
            "OPEL Insignia Grand Sport", "OPEL Mokka-e", "PAGANI Huayra Roadster",
            "PAGANI Huayra Roadster BC", "PAGANI Imola", "PANOZ Esperante GTLM", "PANOZ Avezzano",
            "PANOZ Roadster", "PERODUA Myvi", "PERODUA Alza", "PERODUA Axia",
            "PEUGEOT 5008", "PEUGEOT 508 SW PSE", "PEUGEOT 508 PSE", "Pininfarina Battista",
            "Polestar Polestar 1", "Polestar Polestar 2", "PONTIAC Bonneville",
            "PONTIAC Bonneville", "PORSCHE Panamera 4S Sport Turismo", "PORSCHE 911",
            "PROTON Iriz", "PROTON Perdana", "PROTON Ertiga", "QOROS 3 Hatchbach",
            "QOROS 3 City SUV", "QOROS 5", "RENAULT Talisman", "RENAULT Talisman Estate",
            "RENAULT Talisman Estate", "ROLLS-ROYCE Cullinan", "ROLLS-ROYCE Silver Dawn",
            "ROLLS-ROYCE Ghost", "ROLLS-ROYCE Phantom", "SALEEN S7", "SALEEN S7", "SAMSUNG SM 5",
            "SAMSUNG SM 7", "SANTANA PS 10 Pickup", "SANTANA PS 10 Shortline", "SANTANA 300 - 350",
            "SATURN Astra", "SATURN Aura", "SATURN Outlook", "SCION iQ", "SCION iA", "SCION iM",
            "SEAT Leon 5 doors", "SEAT Leon Sportstourer", "SEAT Ateca", "SKODA Octavia Scout",
            "SKODA Octavia Scout", "SKODA Enyaq iV", "SMART EQ fortwo", "SMART EQ fortwo Cabrio",
            "SMART EQ forfour", "SPYKER C8 Double 12 S", "SPYKER C12 LaTurbie",
            "SPYKER C8 Preliator", "SSANGYONG Korando", "SSANGYONG Korando", "SSANGYONG Tivoli",
            "SUBARU WRX STI", "SUBARU Legacy", "SUBARU Outback", "SUZUKI Ignis", "SUZUKI Swift",
            "SUZUKI Swace", "TATA MOTORS Altroz", "TATA MOTORS Harrier", "TATA MOTORS Nexon",
            "TESLA MOTORS Roadster", "TESLA MOTORS Model S", "TESLA MOTORS Cybertruck",
            "TESLA MOTORS Model X", "TESLA MOTORS Model Y", "TOYOTA Avensis Wagon",
            "TOYOTA Highlander", "TOYOTA Land Cruiser 200", "TVR Chimaera", "TVR 350i Convertible",
            "TVR Griffith", "VAUXHALL Astra Sports Tourer", "VAUXHALL Mokka X",
            "VAUXHALL Zafira Tourer", "VOLKSWAGEN Passat GTE", "VOLKSWAGEN T-Roc Cabriolet",
            "VOLKSWAGEN ID.3", "VOLVO V90", "VOLVO XC90", "WIESMANN GT MF4-CS",
            "WIESMANN MF5 Roadster", "WIESMANN GT MF5", "ZENDER Thirty 7", "ZENDER Escape 6",
            "ZENDER Straight 8", "Zenvo ST1", "Zenvo TS1", "Zenvo TSR-S"
    };

    //all car location, when we random to create location, it can select from this.
    static String[] locationOfAU = {
            "Sydney", "Wollongong", "Newcastle", "Brisbane", "Gold Coast", "Caloundra",
            "Townsville", "Cairns", "Toowoomba", "Adelaide", "Hobart", "Melbourne", "Geelong",
            "Perth", "Canberra", "Jervis Bay", "Norfolk Island", "Christmas Island",
            "Cocos Keeling Islands"
    };
}
